### ISSUE TITLE
Causing crash in garden after recent update

### ISSUE THREAD

**Issue by EnderWolf50** [inglettronald/DulkirMod#38]
I first thought it was some other mod, but after reading the logs and some testing (enabling/disabling the mods) it seems the Dulkir mod is broken for the "Queue Full!" string.

Log:
```
...

Mods:
  [✔] dulkirmod-1.2.5

[23:52:09] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: ---- Minecraft Crash Report ----
WARNING: coremods are present:
Contact their authors BEFORE contacting forge
// Hey, that tickles! Hehehe!
Time: 11/14/23 11:52 PM
Description: Unexpected error
java.lang.NumberFormatException: For input string: "Queue Full!"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at dulkirmod.utils.TabListUtils.parseTabEntries(TablistUtils.kt:87)
	at dulkirmod.DulkirMod.onTick(DulkirMod.kt:116)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_DulkirMod_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1624)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Stacktrace:
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at dulkirmod.utils.TabListUtils.parseTabEntries(TablistUtils.kt:87)
	at dulkirmod.DulkirMod.onTick(DulkirMod.kt:116)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_DulkirMod_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:331)
-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityPlayerSP['Kerati_'/9219, l='MpServer', x=-239.00, y=72.00, z=-54.00], EntityOtherPlayerMP['2morebraincells'/9220, l='MpServer', x=-239.00, y=84.43, z=-54.00]]
	Chunk stats: MultiplayerChunkCache: 206, 206
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: -6.00,71.00,17.00 - World: (-6,71,17), Chunk: (at 10,4,1 in -1,1; contains blocks -16,0,16 to -1,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 47 game time, 6000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 3 total; [EntityOtherPlayerMP['2morebraincells'/9220, l='MpServer', x=-239.00, y=84.43, z=-54.00], EntityPlayerSP['Kerati_'/9219, l='MpServer', x=-239.00, y=72.00, z=-54.00], EntityOtherPlayerMP['2morebraincells'/9220, l='MpServer', x=-239.00, y=84.43, z=-54.00]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (1.4.11) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:347)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2536)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_382, Temurin
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Temurin
	Memory: 1151236248 bytes (1097 MB) / 1684537344 bytes (1606 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9-universal.jar) 
	UCHIJA	oneconfig{0.2.1-alpha182} [OneConfig] (OneConfig (1.8.9-forge).jar) 
	UCHIJA	dulkirmod{1.2.5} [Dulkir Mod] (dulkirmod-1.2.5.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 546.01' Renderer: 'NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2'
	Launched Version: 1.8.9
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2 GL version 4.6.0 NVIDIA 546.01, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 16x AMD Ryzen 7 4800HS with Radeon Graphics 
[23:52:09] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:529]: #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\kerati\AppData\Roaming\PrismLauncher\instances\1.8.9 Test\.minecraft\crash-reports\crash-2023-11-14_23.52.09-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code -1.
Clipboard copy at: 14 Nov 2023 23:52:35 +0800
```

The entire log is too long so I trimmed it a bit, the complete log can be viewd at [https://pastebin.com/vc7LQC54](https://pastebin.com/vc7LQC54)

**Comment by tac-owo** [comment]
I also have this issue, and can confirm it's with DulkirMod, since it happens with just Dulkir in the mods folder.

**Comment by inglettronald** [comment]
Thanks for the report! A fix will be issued shortly

**Comment by EnderWolf50** [comment]
Thank you for such a quick fix! 🥰 I'm gonna close this issue since it already got fixed.
